bencevans/node-sonos

lib/events/listener.js, lib/sonos.js
hi. here are some (hopefully) very-straight forward changes to provide support for generic UPnP audio devices ... the basic hook is to add an optional third parameter to the Sonos() constructor allowing the caller to specify where the endpoints reside (overriding the hard-coded Sonos values.
enjoy!
=> add support for generic UPnP audio

lib/sonos.js
No one seems to have missed it, but I need it at least once a day :-)
I regulary turn off my speakers to save energy (going to sleep, going to work). 10-15 Watts on standby for  my 2x Play:1 and 1x Sub is a little wasteful. And I want even more devices in the future.
I'm using a HomeMatic Button or a ioBroker alarm clock script to turn them on manually or on wakeup.
On wakeup I automatically fill the queue with my morning playlist, set shuffle mode and start playing using node-sonos.
The problem is, the queue ist not selected after power on. Even when I fill it with tracks, commands like play and setPlayMode will fail.
You can test it by yourself. Turn on your speakers, start any Sonos App and try to activate Shuffle, Repeat or Fading. They are grayed out.
Start `sonos.selectQueue();` and …
=> Add queue selection

lib/sonos.js
As the `Sonos.prototype.getMusicLibrary` and `Sonos.prototype.searchMusicLibrary`-methods had quite some code in common I made searchMusicLibrary able to take null as searchTerm-argument and made getMusicLibrary a wrapper function.
=> Removed redundant code in search functions

lib/sonos.js
Hard-code list of Sonos service modules to import. This allows us to browserify this module as browserify requires local module names to be a simple string and not something evaluated.
=> Fix browserify by importing specific modules

API.md, README.md, examples/search.js, lib/sonos.js, test/sonos.test.js
This change more closely mimics what the Sonos desktop add does for device discovery. It fixed some of the discovery issues I was seeing. The desktop app does more yet: is more aggressive with polling, listens for notify messages from Sonos devices.
=> Improve Sonos device discovery robustness

lib/sonos.js, test/sonos.test.js
Added support for passing a Spotify track uri to the ```Sonos.play``` and ```Sonos.queue``` apis.
I added a new helper function named ```optionsFromSpotifyTrackUri(uri)```
This function takes a Spotify uri in the form ```spotify:track:trackid``` and creates an options object of the form:
```
{
uri: "spotify:track:<trackid>",
metadata: "(meta data from original addSpotify function)"
}
```
This helper function is used in the ```Sonos.play``` and ```Sonos.queue``` apis to create the options/metadata object in the case when the caller passes a Spotify track uri.
```Sonos.play``` has been also been changed to call ```Sonos.queue``` rather than ```Sonos.queueNext``` since the SOAP envelope body needed to contain the ```<AddURIToQueue>``` node, which is the default for this api. I also added …
=> Support Spotify track uri for Play and Queue apis

lib/events/listener.js
I'm currently using homebridge-sonos and due to way the event listener works in node-sonos it listens for events on a random port. Unfortunately, I'm running this on a computer with a firewall.
This change adds options API to the listener so a custom fixed port can be specified. I plan to implement this in a contribution to homebridge-sonos. It should fallback gracefully to randomly generating a port if one is not specified.
Thanks!
=> Allow fixed listener port to be specified

lib/sonos.js
This is a fix for [dgram.js:527 throw new Error('Not running'); #4](https://github.com/bencevans/sonos-cli/issues/4) in the [sonos-cli](https://github.com/bencevans/sonos-cli) repo. The fix clears the timeouts (`searchTimer` and `pollTimer`) on the socket `close` event preventing `self.socket.send` from being called with a closed socket, resulting in `Error: Not running`.
=> clear timeouts on socket close

lib/sonos.js
Possible fix for https://github.com/bencevans/node-sonos/issues/157
=> Prevent eventemitter leak while searching for sonos devices

.travis.yml, README.md, examples/listenForEvents.js, lib/events/listener.js, lib/sonos.js
Should fix #194
This way everyone can use the some what difficult event listener.
You can call `startListening` on the `Sonos` device, it will create a `Listener` in the background and start emitting event like `TrackChanged`, `VolumeChanged`, `Muted` and `StateChanged`.
=> feat: Sonos can listen for events

.npmignore, package.json
Switched from using `.npmignore` to the [`files`](https://docs.npmjs.com/files/package.json#files) array in package.json. This results in fewer lines, one less file and we don't need to keep track of which files to exclude.
=> Exclude non-essential files

lib/services/AlarmClock.js, lib/services/Service.js
Fix for #211, where the return of `AlarmClock.ListAlarms()` is wrong.
Not sure what will be impacted by this change.  Alternatively, we could pass an optional parameter to `Service._parseKey()` for `explicitArray`, so each caller has their own say in this.
=> Fix bug in AlarmClock.listAlarms()

lib/helpers.js, lib/services/Service.js, lib/sonos.js
It makes no sense to me to request the current state if the state from the listener (that is saved anyway) is also available.
This means that the library will respond more quickly it the listener is already listening for events for this speaker. We already got the state so that is send back to the user.
=> Data from listener is used

lib/events/eventParser.js, lib/helpers.js
The title of the current track in a radio station is given in the <r:streamContent>-tag which is empty for Spotify playlists.
```xml
<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/">
<item id="-1" parentID="-1" restricted="true">
<res protocolInfo="aac:*:application/octet-stream:*">aac://http://fm02-icecast.mtg-r.net/fm02_aac</res>
<r:streamContent>Tom Petty - Learning To Fly</r:streamContent>
<dc:title>fm02_aac</dc:title>
<upnp:class>object.item</upnp:class>
</item>
</DIDL-Lite>
```
=> Add support for TuneIn radio track titles

lib/helpers.js
If the `albumArtURI` of an item is an `Array`, the first item is picked
With a custom playlist I experienced that the `albumArtURI` could contain multiple paths to album art. That would lead to an error since the `startsWith` function is not defined for an `Array`.
This small change fixes that issue.
Let me know if you need more info on the bug.
=> Handle when albumArtURI is an Array

examples/playTuneinRadio.js, lib/helpers.js
fixed using the proper uri (e.g. getFavourites returns uris already starting with 's')...
encoded the title, since TuneIn does not like unescaped ampersands...
=> fixed TuneIn support

README.md, docs/services/ZoneGroupTopology.md, docs/sonos.md, examples/getplaylists.js, examples/getsonosplaylists.js, examples/search.js, examples/topology.js, lib/events/adv-listener.js, lib/events/eventParser.js, lib/events/listener.js, lib/helpers.js, lib/services/AVTransport.js, lib/services/AlarmClock.js, lib/services/DeviceProperties.js, lib/services/RenderingControl.js, lib/services/Service.js, lib/services/ZoneGroupTopology.js, lib/sonos.js, package-lock.json, package.json
As of Sonos version 9.1 the `getTopology()` endpoint wasn't working anymore.
Some of the information could also be found in the `ZoneGroupTopologyService`.
With this PR we will get a new `getAllGroups()` function on the Sonos speaker, and this is also used in the `joinGroup` command.  
This will fix #332
=> New way to Fetch the groups

lib/sonos.js
Apparently ZPSupportInfo can sometimes just be an empty string, in which case there are no zones or media servers to find.
=> Don't fail if ZPSupportInfo is empty

lib/events/eventParser.js
This fixes a bug that would cause the ZoneGroupTopology event to not be emitted because map was being called on an object when an array was expected.
This error consistently popped up when I grouped all my Sonos speakers together into one group. ZoneGroup was an object in this case and would throw an error.
Error:
```bash
(node:30873) UnhandledPromiseRejectionWarning: TypeError: eventData.ZoneGroupState.ZoneGroups.ZoneGroup.map is not a function
at Object.EventParser._parseZoneGroupTopologyEvent (/Users/nicholasvillarreal/Developer/ByteGenesis/sonos-web/server/node_modules/sonos/lib/events/eventParser.js:124:69)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:188:7)
(node:30873) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated …
```
=> Fix bug in eventParser when constructing data for ZoneGroupTopology event

lib/sonos.js
Changed encodeURIComponent to encodeURI to allow for forward slashes within the search term. This allows for deeper browsing/searching which was not possible before as any forward slashes would have been lost to conversion.
```javascript
// Before
encodeURIComponent('Blues/B.B. King')
// -> Blues%2FB.B.%20King
// With change
encodeURI('Blues/B.B. King')
// -> Blues/B.B.%20King
```
=> Add ability for more complex searchTerm

lib/helpers.js, test/sonos.test.js
This helps to manage Playlists as you can get real id of playlist.
Added unit test with sonos_playlists lookup
=> expose items id and parentID

lib/services/ZoneGroupTopology.js
`zoneGroupState.ZoneGroups.ZoneGroup` is not always an array, which lead to `ZoneGroup.ZoneGroupMember` also not being an array.
This fixes an issue where `sonos-cli` list commands fail with `TypeError: zone.ZoneGroupMember.find is not a function`
I'm not sure if this issue should be fixed here or in `sonos-cli` though.
=> Fix issue when groups is not an array

examples/playTuneinRadio.js
Original documentation says that the radio ID for method "playTuneinRadio" has a leading "s". 
But the method only works without leading "s". 
I suggest modifying the documentation.
=> Error in documentation
