- lib/sonos.js
I noticed that the function getMusicLibrary doesn't return the album art and artist, so i checked the original data and found the values dc:creator and upnp:albumArtURI and added these to the return values.
> added artist and albumArtURL to getMusicLibrary

- lib/sonos.js
Select a specific track in queue by number
> Add track selection

- examples/collectinfo.js
Add example how to collect and process search info
> Add new example

- examples/searchLibrary.js
- lib/sonos.js
I have added a new function to allow you to search library
I have also amended the queue next function to be able to pass in an object with metadata
> Search library

- examples/addSpotify.js
- lib/sonos.js
works for me, test it out and let me know if it works for you.
The weird thing is the random number, if I just always use this it works but if I use the truly random one it does not. Not sure what they use that for..maybe you know more.
> added helper method to add a track from spotify

- lib/sonos.js
I noticed that the search was broken and returning the whole library rather than just for the search term entered.
This should fix it
> corrected search

- lib/sonos.js
- test/sonos.test.js
Needed to have an event emitted when the timeout was complete.
Added one in, don't think this will be valid for the 1.x release though.
> Feature: Added timeout event and unit tests

- API.md
- examples/radio.js
- lib/sonos.js
- test/sonos.onsite.test.js
This PR adds support for favorites radio (stations or shows)
> Add support for Favorites Radio

- API.md
- examples/getsonosplaylists.js
- lib/sonos.js
- test/sonos.onsite.test.js
This allows to retrieve the sonos playlists using: `getMusicLibrary('sonos_playlists')`
> Add support for Sonos Playlists

- API.md
- README.md
- lib/sonos.js
Hello
This is another one for specifying port. This allows the options to contain a port that is passed to the datagram bind. Helps me configure my firewall 👍 
Thanks
> Allow the UDP discovery bind port to be specified

- .npmignore
- examples/addSpotify.js
- examples/getplaylists.js
- examples/getsonosplaylists.js
- examples/next.js
- examples/play.js
- examples/transportEvent.js
- examples/tts.js
- lib/services/Service.js
- lib/sonos.js
- package.json
> Cleaned some code and added track uri for radio/spotify

- examples/transportEvent.js
- lib/events/listener.js
Bug-bashing mode ON
Really small change this time.
> Listener options, with interface name FIX #140

- lib/sonos.js
To fix an issue when the search times out but the poller timer is still active
> Clear the pollTimer when the connection on timeout

- lib/services/GroupRenderingControl.js
- lib/sonos.js
Added GroupRenderingControl service.
> Issue #152

- API.md
- README.md
- examples/addSpotify.js
- lib/sonos.js
- test/sonos.test.js
using the new method should fix the problems in #142
> add setSpotifyRegion method

- lib/sonos.js
Possible fix for https://github.com/bencevans/node-sonos/issues/161
> Check if albumArtURL starts with http

- lib/services/AVTransport.js
- lib/sonos.js
I added the configureSleepTimer command.
You need to provide the time as "hh:mm:ss".
> Added ConfigureSleepTimer

- examples/getsonosfavorites.js
- lib/sonos.js
https://github.com/bencevans/node-sonos/issues/177
> Get favorites from sonos

- README.md
- examples/getplaymode.js
- lib/sonos.js
- package-lock.json
> feat: .getPlayMode(cb)

- lib/sonos.js
- test/sonos.test.js
https://github.com/bencevans/node-sonos/issues/185
> Fix for issue 185

- lib/sonos.js
This is something I am wanting for a project I'm working on myself and I figured I'd open a PR since this is a small change and could be useful to others.
> Add the track's position in the queue to the data returned from currentTrack()

- examples/switchToLineIn.js
This is only possible since the pull-request #200
Should clearify #148
> docs(Example): Added sample to switch to line-in

- README.md
- examples/groupManagement.js
- lib/sonos.js
- package.json
I Implemented really easy to use group controls. If you decide you want a player to join a group. You just need the name of one of the members of that group and it will automatically find the group coordinator and join it.
One more issue gone, 10 to go....
> Cool group controls

- API.md
- README.md
- examples/alarmService.js
- lib/services/AlarmClock.js
- lib/services/Service.js
- lib/sonos.js
Done some work on the alarm service, it is now available in the main library.
```node 
var alarmService = sonos.alarmClockService()
```
Fixes #160 hope you like it
> Alarm stuff

- package-lock.json
- package.json
Warnings for a vulnerbility in mustache. jsdox doesn't appear to be maintained anymore so switching to an updated fork
> Switch to jsdox fork

- .npmignore
- package-lock.json
- package.json
Fixing issues mentioned at https://github.com/bencevans/node-sonos/pull/209#discussion_r160795630
> fix: correct dep to devDep & update jsdox fork name

- test/sonos.test.js
> Update tests to use mockRequest and work with returned promises

- docs/sonos.md
- examples/switchToLineIn.js
- lib/deviceDiscovery.js
- lib/events/adv-listener.js
- lib/events/eventParser.js
- lib/helpers.js
- lib/services/RenderingControl.js
- lib/sonos.js
- package-lock.json
- package.json
- Added `getName()` to sonos, it disappeared when on the async transformation. Fixes #253
- Added `coordinatorOnly` parameter to joinGroup command. Fixes #241 
- Whitespaces (damn standard rules).
- Package update
> Some small fixes

- lib/helpers.js
allow queueing of amazonprime playlists.
(NOTE: spotifyregion is reused for now, and only 51463 has been verified so far)
> added amazonprime queue

- test/sonos.test.js
Timeout cleared in the event of test passing
> fix issue #362

- lib/sonos.js
- test/sonos.test.js
Hey everyone,
I figured out that there is an issue with the playmode. 
Would you please so kind, have a look and merge the pull request?
Thanks a lot :-)
BTW: Awesome project 👍
> Bugfix for playmode undefined

- docs/services/AVTransport.md
- docs/sonos.md
- examples/getQueue.js
- examples/queue.js
- lib/services/AVTransport.js
- lib/sonos.js
> feat: Added removing items from the queue

- README.md
I have created a Sonos controller [for the web browser](https://github.com/Villarrealized/sonos-web) thanks to all you wonderful folks and contributors to this great library. I have a lot more features planned for this app, but I hope you all have a chance to try it out and let me know what you think.
Merry Christmas!
> Add sonos-web to Apps section in README

- examples/playlist.js
- lib/helpers.js
- lib/services/AVTransport.js
- lib/services/ContentDirectory.js
- lib/sonos.js
- test/sonos.test.js
Hi everyone,
I added some new functionality for creating playlists and also for deleting them.
Please have a look over it :-)
> feat: add/delete playlist, add/remove songs to/from playlist

- lib/helpers.js
Adds support for generating proper metadata in order to play SoundCloud playlists & Likes.
> feat: Add SoundCloud support to GenerateMetadata

- lib/events/eventParser.js
- lib/services/ZoneGroupTopology.js
It appears Sonos v10.1 started nesting the data an additional level.
Fixes #407
> fix: nested ZoneGroupState data unpacking if necessary.

- README.md
- examples/deviceDiscovery.js
- lib/asyncDeviceDiscovery.js
- lib/sonos.js
- lib/sonosGroup.js
- test/sonos.test.js
- Async device discovery
- Extended `getAllGroups()` method
- Fixed #420 
- Fixed #421
> feat: Extended groups and async device discovery

- .travis.yml
- examples/playTuneinRadio.js
- lib/sonos.js
- package-lock.json
- package.json
I've managed to tackle the issue with notifications while playing some sort of stream.
These streams didn't allow setting the Relative track time and/or the number in the queue. This now added some tests to see if it should try to set the track/RelTime and if they still get triggered but fail it is catched and written to debug for those that are listening.
To see the debug statements try run the following code (replace IP) `DEBUG=sonos:main SONOS_HOST=192.168.x.x node examples/playNotification.js`
> Fixing Notifications for streams

- lib/sonos.js
References tim-hellhake/sonos-adapter#9
> Fix URL undefined error.

- package-lock.json
Upon npm install, I found 3 vulnerabilities, so I updated the dependencies (npm audit fix) and pushing them back for you to update the node-sonos package.
> fix: dependency upgrade to resolve vulnerabilities warnings

- README.md
- lib/services/ContentDirectory.js
- lib/services/Service.js
- lib/sonos.js
- test/sonos.test.js
Tried to fix a lot of currently open issues.
Be sure to test before releasing. I'm not really sure about the error handling in the service file.
This was suggested by @hklages  in #448
> Bug bashing

- lib/helpers.js
- lib/sonos.js
Addresses malformed device XML, see #465
> Sanitizing malformed device description XML

- lib/services/AVTransport.js
- lib/services/AlarmClock.js
- lib/services/AudioIn.js
- lib/services/ContentDirectory.js
- lib/services/DeviceProperties.js
- lib/services/GroupManagement.js
- lib/services/GroupRenderingControl.js
- lib/services/MusicServices.js
- lib/services/RenderingControl.js
- lib/services/Service.js
- lib/services/SystemProperties.js
- lib/services/ZoneGroupTopology.js
- lib/sonos.js
Hello,
I started going through a few of the additional bits I have implemented in my unofficial controller for linux, and started backporting them into node-sonos. As you can see I have a whole set of bits I have had to extend, to make several functionality bits work:
https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/tree/master/src/ui/services/enhanced
In the past I have been crap at feeding back into this awesome library, and this time I want to do it right and make a meaningful contribution if I can.
My goal is to bit by bit move as much functionality back to node-sonos as possible and then cut it out of my code base, where that makes sense of course.
I also am aiming to write a bit more detailed comments about some of the workflows I have discovered, i.e. the …
> ES6 classes for services plus some additional methods 

- examples/switchToLineIn.js
and adds detail to second example that it will also work for SONOS Connect.
@all-contributors :)
> fix(example-line-in): fixes typos

- README.md
Adding my app to the list of "in the wild" usage
> doc: add groove sensor to docs
